# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install deps & Build & Generate
        run: |
          npm i
          npm run build
          npm run generate

      # Deploy built frontend
      # Way to deploy built app to VPS
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          # REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          # Source directory
          SOURCE: 'dist/, .nuxt/'
          # Target directory
          TARGET: '/var/hedonist-frontend-nuxt' # optional, default is /home/REMOTE_USER/
          # Arguments to pass to rsync
          # ARGS: # optional, default is -rltgoDzvO
          # An array of folder to exclude
          # EXCLUDE: '/dist/, /node_modules/'

      - name: Restart pm2 process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            pm2 restart hedonist-frontend-nuxt
          # cd ~/../var/hedonist-backend-strapi
          # yarn install
          # pm2 restart hedonist-backend-strapi
